### ISSUE TITLE
Where are the metadata.dependencies for buildpack.toml?

### ISSUE THREAD

**Issue by drnic** [paketo-buildpacks/java#1]
The https://github.com/paketo-buildpacks/java/blob/master/buildpack.toml file is missing `[[metadata.dependencies]]` section, such as found in https://github.com/paketo-community/ruby/blob/master/buildpack.toml#L10-L17

I'm looking for the `procfile` dependency from https://github.com/paketo-buildpacks/procfile/issues/3

Could CI please curate buildpack.toml to include the metadata.dependencies being used for the `:latest` OCI?

**Comment by drnic** [comment]
I tried to look inside the java OCI to find the fully-formed `buildpack.toml` (is it there?) but neither `bash` nor `sh` included in the image:

```
$ docker run -ti gcr.io/paketo-buildpacks/java bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown.
$ docker run -ti gcr.io/paketo-buildpacks/java sh
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"sh\": executable file not found in $PATH": unknown.
```

**Comment by drnic** [comment]
Perhaps https://github.com/paketo-buildpacks/java/blob/master/buildpack.toml needs to be renamed `buildpack.toml.template` for CI; and the latest working version produced by CI is called `buildpack.toml`?

**Comment by nebhale** [comment]
The `buildpack.toml` included in this repository is not a template, it's a fully valid document.  [Buildpackages](https://github.com/buildpacks/spec/blob/master/distribution.md#buildpackage) are not builders and do not have an OS within them, just layers representing the filesystem a buildpack or buildpacks contained within them.  You'll notice that `package.toml` [contains the pointers to where to download the necessary component buildpackages](https://github.com/paketo-buildpacks/java/blob/master/package.toml).

**Comment by drnic** [comment]
Thanks. Is this repo a buildpack or a buildpackge? How do I "build it"?

```
$ pack package-buildpack java --package-config package.toml
ERROR: reading config: missing buildpack.uri configuration
```

**Comment by nebhale** [comment]
Since we covered this in Slack, do you mind if I close it?
