### ISSUE TITLE
Unable to build java buildpack locally

### ISSUE THREAD

**Issue by c0d1ngm0nk3y** [paketo-buildpacks/java#1401]
When trying to package the java buildpack locally in order to use it for tests, we run into an error with the current content of the `package.toml`.

```
ERROR: reading config: unknown configuration element targets in ./target/package.toml
```

We used the command `pack buildpack package` with the latest version of `pack` (0.33.2)

## Expected Behavior

With the state in `main`, we should always be able to create a local package of the buildpack.

## Current Behavior

It only works if we modify the `package.toml` and remove the mentions of "targets".

## Steps to Reproduce

Use the `Makefile` provided in #1399 and call `make package`

## Motivations

Integration tests should run with a local version.

How does the release work? Isn't the same `pack` command needed there?

**Comment by anthonydahanne** [comment]
Hello @c0d1ngm0nk3y 
As replied in Slack
> We are currently using an experimental version of pack
> there are 2 two ways to get it:
> * we have a [built x86_64 binary](https://github.com/paketo-buildpacks/spring-boot/blob/main/.github/workflows/pb-create-package.yml#L52)
> * or you can build from source
> to build from source,
> git clone pack repo, checkout pr-2086 and run make, you'll get it under bin
> * or finally, you can wait for the official release, this week or next week
