### ISSUE TITLE
buildpack paketo-buildpacks/ca-certificates@3.8.2 is broken

### ISSUE THREAD

**Issue by PackiarajSakkananGW** [paketo-buildpacks/java#1463]
buildpack `paketo-buildpacks/ca-certificates@3.8.2` is broken
refer: https://github.com/paketo-buildpacks/ca-certificates/issues/235

paketo-buildpacks/ca-certificates@3.8.2 dependency cause build to fail with below error message 

## Expected Behavior
Should be able to build

## Current Behavior
Build failed with error message 

>     message: 'validating buildpack paketo-buildpacks/ca-certificates@3.8.2: stack
>       io.buildpacks.stacks.jammy is not supported'

## Possible Solution
upgrade to paketo-buildpacks/ca-certificates@3.8.3

## Steps to Reproduce
try any getting started guide in kpack/pack

## Motivations
Getting started tutorial is itself failing and unable to use java buildpack because of its dependency to `paketo-buildpacks/ca-certificates@3.8.2`

**Comment by dmikusa** [comment]
The fix for this is in ca-certificates@3.8.3 and that's been merged into the main branch, so the fix will go out in the next release of the paketo-buildpacks/java buildpack. That is usually every Friday.

**Comment by dmikusa** [comment]
This has been released. Closing.
