### ISSUE TITLE
Yarn dependency (v1.3.8) pakages throws 404 (File does not exists) -  java buildpack (15.2.0) 

### ISSUE THREAD

**Issue by doddisam** [paketo-buildpacks/java#1505]
Hello Team,

We tried using latest java buildpack (15.2.0) and we do see issues with yarn(v1.3.8) dependency packages. Looks like the file does not exists in the repository?
Download of https://deps.paketo.io/yarn/yarn_1.22.19_linux_noarch_bionic_3235ba55.tgz failed with error https://deps.paketo.io/yarn/yarn_1.22.19_linux_noarch_bionic_3235ba55.tgz: status code 404

Do we have any plans to release java buildpack with latest yarn?

-Sameer

**Comment by rkreddy78** [comment]
I am facing similar issues, can someone , please look into it

**Comment by dmikusa** [comment]
This was an external problem. The location of these was changed by the CFF, and unfortunately, it breaks older buildpacks. The Yarn buildpack has been released with this fixed & the v16.0.0 Java buildpack has this as well.

I'm going to close this out as it should be resolved. If folks are still hitting this issue, please reach out.
