### ISSUE TITLE
Change default BP_JVM_VERSION from 17 to 21

### ISSUE THREAD

**Issue by c0d1ngm0nk3y** [paketo-buildpacks/java#1574]
## Describe the Enhancement

Change the default java version from 17 to 21 (see [RFC 14](https://github.com/paketo-buildpacks/rfcs/blob/main/text/java/0014-selecting-default-java-version.md))

* [x] sap-machine: https://github.com/paketo-buildpacks/sap-machine/pull/445
* [x] adoptium: https://github.com/paketo-buildpacks/adoptium/pull/493
* [x] amazon-corretto: https://github.com/paketo-buildpacks/amazon-corretto/pull/383
* [x] alibaba-dragonwell: https://github.com/paketo-buildpacks/alibaba-dragonwell/pull/282
* [x] azul-zulu: https://github.com/paketo-buildpacks/azul-zulu/pull/488
* [x] bellsoft-liberica: https://github.com/paketo-buildpacks/bellsoft-liberica/pull/726
* [x] eclipse-openj9: https://github.com/paketo-buildpacks/eclipse-openj9/pull/463
* [x] graalvm: https://github.com/paketo-buildpacks/graalvm/pull/422
* [x] microsoft-openjdk: https://github.com/paketo-buildpacks/microsoft-openjdk/pull/280
* [x] oracle: https://github.com/paketo-buildpacks/oracle/pull/265
* [x] Announcement ([comment](https://github.com/paketo-buildpacks/sap-machine/pull/445#issuecomment-2396877093), [blog pr](https://github.com/paketo-buildpacks/blog/pull/73))
 
## Motivation

[RFC 14](https://github.com/paketo-buildpacks/rfcs/blob/main/text/java/0014-selecting-default-java-version.md)

**Comment by dmikusa** [comment]
Wow! Thank you so much for opening up all these PRs and helping to drive this effort. Much appreciated.

I've got the Slack/Discussion notifications done. And a PR for a blog entry drafted https://github.com/paketo-buildpacks/blog/pull/73. I'm working to get that published ASAP.

The plan will be to merge these towards the end of the month & cut individual releases. Then we'll cut a composite Java release with an updated Bellsoft Liberica late Oct 31st or early on Nov 1.

**Comment by dmikusa** [comment]
Ok, those are all merged and I've cut releases of the component buildpacks. We'll merge that change into the Java & Java Native Image buildpacks later this week.

**Comment by anthonydahanne** [comment]
Perfect! thanks @dmikusa and @c0d1ngm0nk3y !

**Comment by anthonydahanne** [comment]
completed in latest build: https://github.com/paketo-buildpacks/java/releases/tag/v17.0.0
