### ISSUE TITLE
How to include `curl` when using builder:base?

### ISSUE THREAD

**Issue by albanf** [paketo-buildpacks/java#171]
## What happened?

* What were you attempting to do?
I was trying to setup a docker health check against a Spring Boot application, using the default builder (base)

* What did you expect to happen?
I was expected curl or a similar utility to be available to query `http://localhost:8080/actuator/health`

* What was the actual behavior? Please provide log output, if possible.

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.
Using `spring-boot-maven-plugin` 2.4.3 and image builder: `docker.io/paketobuildpacks/builder:base`

## Workaround

It works using image builder `docker.io/paketobuildpacks/builder:full`, but the image size grows from 334 MB to 931 MB.

`curl` could be included in the base stack as well as the full stack but some people might prefer to keep the base image as small as possible.

I guess having an optional buildpack contributing some utilities would be a better option?

Are there any other option?

**Comment by dmikusa-pivotal** [comment]
At the moment, you have the choice of using the full builder if you'd like more dependencies installed. There isn't an easy way to cherry-pick specific other dependencies that you want to be included in the base image.

There is a concept of mixins, but these are just tags to indicate requirements. It does not provide you with an image containing those dependencies. I believe there is work being done to make this easier under the [stack packs RFC, but it's not complete yet](https://github.com/buildpacks/rfcs/blob/main/text/0069-stack-buildpacks.md).

It is possible to build your own customized image and use that, but it's a non-trivial amount of work, plus it puts you on the hook to update your image or **risk not getting critical security updates**.

**I would recommend just using the full image if it has what you need**. The additional size perceived is significant when compared to the base image, but it's insignificant when compared to the amount of storage available in modern systems and when you consider that the storage size consumed is not 931M * the number of containers using that image, but, roughly speaking, 931M for the base layers + (additional app specific size per container * number of containers) (tl;dr images are efficiently stored and common layers are deduplicated).

I'm going to close this as there's nothing that can be done at the Java level to handle this. Hope that helped.

**Comment by albanf** [comment]
The main consequence of the increased size for us is the increase in startup time (we use AWS Fargate)
~250 MB => pull takes ~15s
~1 G => pull takes ~45s

We'll use the full builder for now.

Do you know what would be the correct repository to ask more questions about recommend setup for docker health checks with buildpacks? I guess if the target is Kubernetes, then it's fine because the http probe don't run within the container, but I think a lot of people use platforms that really on Docker health checks...

**Comment by dmikusa-pivotal** [comment]
>Do you know what would be the correct repository to ask more questions about recommend setup for docker health checks with buildpacks?

I would suggest asking in the Paketo Slack: paketobuildpacks.slack.com. You could ask in the #buildpacks channel and see what others are using.

Another option would be coding up a health check client into your application code. Using [URLConnection](https://docs.oracle.com/javase/8/docs/api/java/net/URLConnection.html) you could set this up without too much fuss. Then your health check command could run `java` and execute your client (just watch your memory usage, maybe set `-Xmx` and others) as low as possible on the client.

**Comment by dmikusa-pivotal** [comment]
Just as an FYI, I have opened an RFC to recommend adding a health check buildpack, please see https://github.com/paketo-buildpacks/rfcs/pull/183 for details.
