### ISSUE TITLE
Can't run simple app on heroku due to memory calculator

### ISSUE THREAD

**Issue by jarias** [paketo-buildpacks/java#2]
On early versions I was able to run a simple spring boot app on Heroku's free tier suing paketo but now I get:

```
2020-08-14T20:23:31.670371+00:00 app[web.1]: required memory 819590K is greater than 512M available for allocation: -XX:MaxDirectMemorySize=10M, -Xmx400M, -XX:MaxMetaspaceSize=102790K, -XX:ReservedCodeCacheSize=240M, -Xss1M x 50 threads
```
Is there a way to disable the memory calculator and pass my own JVM memory settings?

**Comment by nebhale** [comment]
You can set any valid JVM memory flag (the ones in the log message are the pertinent ones) and the calculator will take that setting into account when calculating the rest.

Note though, that your explicit setting of `-Xmx400M` plus the JVM's default `ReservedCodeCache` of `240M` _already_ exceed the container size of `512M`.  You can try to decrease the JVM's default configuration but doing so will result in a drastic performance penalty when the JIT is forced to evict earlier optimizations from the `ReservedCodeCache`.

**Comment by jarias** [comment]
Thanks for the info, I know the risk of bad memory config, but is good to know I can still controll it at my own risk
