### ISSUE TITLE
Expose PORT variable in order to run images where PORT must be defined/exposed

### ISSUE THREAD

**Issue by cf-buildpacks-eng** [paketo-buildpacks/java#243]
## What happened?

I am unable to deploy my image to google cloud run due to the inability to expose/set $PORT when using Java CNB. 

```Cloud Run error: Container failed to start. Failed to start and then listen on the port defined by the PORT environment variable. Logs for this revision might contain more information. ``` <-- Error from Google Cloud run

* What were you attempting to do?
  Built a Spring Boot application with the Java CNB and Pack. Attempted to deploy container in Google Cloud Run with image and received above error

* What did you expect to happen?
   I expected the container to deploy properly as Java by default sets HTTP listener on 8080. 

* What was the actual behavior? Please provide log output, if possible.
  Container failed to start. (See above error output)

## Build Configuration

Basic Spring boot test application with single controller endpoint. Using gradle. Attempted with server.port=${PORT:8080} as well as leaving absent from application.properties

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

any generic spring boot app will replicate the issue.

NOTE: I used a generic dockerfile to build the same test application with ```EXPOSE 8080``` and was able to successfully deploy to google cloud run.

**Comment by shanks3012** [comment]
Apologies, created issue on wrong account. Let me know if I should open a new issue under my account.

**Comment by dmikusa-pivotal** [comment]
So for a Spring Boot app, I do not believe the buildpack will set anything regarding the port on which the app should listen. Spring Boot will default to listen on port 8080. You can change that with standard Spring Boot conventions, for example, by setting `SERVER_PORT=9090` or whatever port you want to use.

Ex:

```
docker run -e SERVER_PORT=9090 demo:0.0.1-SNAPSHOT
Setting Active Processor Count to 6
Calculating JVM memory based on 9067752K available memory
Calculated JVM Memory Configuration: -XX:MaxDirectMemorySize=10M -Xmx8672856K -XX:MaxMetaspaceSize=87695K -XX:ReservedCodeCacheSize=240M -Xss1M (Total Memory: 9067752K, Thread Count: 50, Loaded Class Count: 13069, Headroom: 0%)
Adding 129 container CA certificates to JVM truststore
Spring Cloud Bindings Enabled
Picked up JAVA_TOOL_OPTIONS: -Djava.security.properties=/layers/paketo-buildpacks_bellsoft-liberica/java-security-properties/java-security.properties -agentpath:/layers/paketo-buildpacks_bellsoft-liberica/jvmkill/jvmkill-1.16.0-RELEASE.so=printHeapHistogram=1 -XX:ActiveProcessorCount=6 -XX:MaxDirectMemorySize=10M -Xmx8672856K -XX:MaxMetaspaceSize=87695K -XX:ReservedCodeCacheSize=240M -Xss1M -Dorg.springframework.cloud.bindings.boot.enable=true

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.4.4)

2021-06-17 18:54:26.959  INFO 1 --- [           main] io.paketo.demo.DemoApplication           : Starting DemoApplication v0.0.1-SNAPSHOT using Java 1.8.0_292 on 069cbb094d10 with PID 1 (/workspace/BOOT-INF/classes started by cnb in /workspace)
2021-06-17 18:54:26.964  INFO 1 --- [           main] io.paketo.demo.DemoApplication           : No active profile set, falling back to default profiles: default
2021-06-17 18:54:28.701  INFO 1 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 2 endpoint(s) beneath base path '/actuator'
**2021-06-17 18:54:29.329  INFO 1 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port 9090**
2021-06-17 18:54:29.348  INFO 1 --- [           main] io.paketo.demo.DemoApplication           : Started DemoApplication in 2.991 seconds (JVM running for 3.641)
```

Spring Boot is flexible in how you set the port on which to listen. You could set it in application.properties|yml, as a system property or as an argument (i.e. `--server.port=9090`). 

If you're on a system that is exposing a port dynamically to you through an env variable, you probably want to do something like `SERVER_PORT=$PORT` or `--server.port=$PORT` (I believe the latter is what happens on CF).
