### ISSUE TITLE
Build JEE Image with Pack

### ISSUE THREAD

**Issue by CodeClinch** [paketo-buildpacks/java#42]
I tried to create a image based on java buildpack. But it fails with the following error.

```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:10 min
[INFO] Finished at: 2020-11-02T13:10:10Z
[INFO] ------------------------------------------------------------------------
unable to invoke layer creator
unable to contribute application layer
unable to resolve artifact
unable to find single built artifact in target/*.[jw]ar, candidates: []
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 145
```

**Reproduction**
Steps
download jee application from internal github
pack build espm-web --builder paketobuildpacks/builder:base

**Comment by nebhale** [comment]
@CodeClinch The idea of building a “JEE application” isn’t quite specific enough.  A more specific question might be what kind of artifact you want to run.  For example, as the error message describes, we _will_ handle a WAR file, a standard JEE application type, successfully.  What kind of artifact are you trying to package?

**Comment by dmikusa-pivotal** [comment]
@CodeClinch - This issue has been open a while, but I wanted to follow up and let you know that we do have some support in buildpacks for the behavior you're requesting. We have recently added the OpenLiberty and Apache Tomee application servers, in addition to Apache Tomcat which was previously present, to the buildpacks. 

If you're still interested in this functionality, you may check out the documentation here for instructions on selecting one of these alternative application servers: https://paketo.io/docs/howto/java/#use-an-alternative-java-application-server

I'm going to close this issue out. If you hit any issues or have further feedback, please feel free to open a new issue on the relevant repo. Thanks!
