### ISSUE TITLE
Maven Buildpack fails with code 145

### ISSUE THREAD

**Issue by pax95** [paketo-buildpacks/java#570]
When running the Maven Buildpack 6.5.0 on Circleci the task fails with Code 145.

Bellow is the output from the process

Paketo Maven Buildpack 6.5.0
  https://github.com/paketo-buildpacks/maven
  Build Configuration:
    $BP_MAVEN_BUILD_ARGUMENTS  -Dmaven.test.skip=true --no-transfer-progress package  the arguments to pass to Maven
    $BP_MAVEN_BUILT_ARTIFACT   target/*.[ejw]ar                                       the built application artifact explicitly.  Supersedes $BP_MAVEN_BUILT_MODULE
    $BP_MAVEN_BUILT_MODULE                                                            the module to find application artifact in
    $BP_MAVEN_DAEMON_ENABLED   false                                                  use maven daemon
    $BP_MAVEN_POM_FILE         pom.xml                                                the location of the main pom.xml file, relative to the application root
    Creating cache directory /home/cnb/.m2
  Compiled Application: Contributing to layer
    Executing mvnw --batch-mode -Dmaven.test.skip=true --no-transfer-progress package
      Unable to parse command line options: Unrecognized option: --no-transfer-progress
      
      usage: mvn [options] [<goal(s)>] [<phase(s)>]
      
      Options:
       -am,--also-make                        If project list is specified, also
                                              build projects required by the
                                              list
       -amd,--also-make-dependents            If project list is specified, also
                                              build projects that depend on
                                              projects on the list
       -B,--batch-mode                        Run in non-interactive (batch)
                                              mode (disables output color)
       -b,--builder <arg>                     The id of the build strategy to
                                              use
       -C,--strict-checksums                  Fail the build if checksums don't
                                              match
       -c,--lax-checksums                     Warn if checksums don't match
       -cpu,--check-plugin-updates            Ineffective, only kept for
                                              backward compatibility
       -D,--define <arg>                      Define a system property
       -e,--errors                            Produce execution error messages
       -emp,--encrypt-master-password <arg>   Encrypt master security password
       -ep,--encrypt-password <arg>           Encrypt server password
       -f,--file <arg>                        Force the use of an alternate POM
                                              file (or directory with pom.xml)
       -fae,--fail-at-end                     Only fail the build afterwards;
                                              allow all non-impacted builds to
                                              continue
       -ff,--fail-fast                        Stop at first failure in
                                              reactorized builds
       -fn,--fail-never                       NEVER fail the build, regardless
                                              of project result
       -gs,--global-settings <arg>            Alternate path for the global
                                              settings file
       -gt,--global-toolchains <arg>          Alternate path for the global
                                              toolchains file
       -h,--help                              Display help information
       -l,--log-file <arg>                    Log file where all build output
                                              will go (disables output color)
       -llr,--legacy-local-repository         Use Maven 2 Legacy Local
                                              Repository behaviour, ie no use of
                                              _remote.repositories. Can also be
                                              activated by using
                                              -Dmaven.legacyLocalRepo=true
       -N,--non-recursive                     Do not recurse into sub-projects
       -npr,--no-plugin-registry              Ineffective, only kept for
                                              backward compatibility
       -npu,--no-plugin-updates               Ineffective, only kept for
                                              backward compatibility
       -nsu,--no-snapshot-updates             Suppress SNAPSHOT updates
       -o,--offline                           Work offline
       -P,--activate-profiles <arg>           Comma-delimited list of profiles
                                              to activate
       -pl,--projects <arg>                   Comma-delimited list of specified
                                              reactor projects to build instead
                                              of all projects. A project can be
                                              specified by [groupId]:artifactId
                                              or by its relative path
       -q,--quiet                             Quiet output - only show errors
       -rf,--resume-from <arg>                Resume reactor from specified
                                              project
       -s,--settings <arg>                    Alternate path for the user
                                              settings file
       -t,--toolchains <arg>                  Alternate path for the user
                                              toolchains file
       -T,--threads <arg>                     Thread count, for instance 2.0C
                                              where C is core multiplied
       -U,--update-snapshots                  Forces a check for missing
                                              releases and updated snapshots on
                                              remote repositories
       -up,--update-plugins                   Ineffective, only kept for
                                              backward compatibility
       -v,--version                           Display version information
       -V,--show-version                      Display version information
                                              WITHOUT stopping build
       -X,--debug                             Produce execution debug output
unable to invoke layer creator
unable to contribute application layer
error running build
exit status 1
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 145

**Comment by dmikusa-pivotal** [comment]
The suggested solution here would be to use a newer version of Maven. The flag mentioned in the error, `--no-transfer-progress` is from Maven 3.6.1 (2019). You should use a version of Maven newer than that.

By default, the buildpack will install a version of Maven that is newer than 3.6.1 and compatible with this argument. However, if you are using Maven Wrapper, then the version of Maven is dictated by the Maven wrapper present in your application. You likely need to update your Maven wrapper so it's using a newer version. Then next time you build, the buildpack will use that version of Maven.

If you cannot update Maven for some reason, set the env variable `BP_MAVEN_BUILD_ARGUMENTS` to `-Dmaven.test.skip=true package` with `pack build -e BP_MAVEN_BUILD_ARGUMENTS='-Dmaven.test.skip=true package'`. That will override the default set of Maven arguments and remove the one incompatible with your older version of Maven.

**Comment by pax95** [comment]
The project is not using any wrapper and will rely on the maven buildpack for taking action on installing the correct maven version. I have verified that this is happening on a java 17 project, but not when java 11 project ??
Here is the output from the java 17 project where maven is contributing ->
Paketo Maven Buildpack 6.5.0
  https://github.com/paketo-buildpacks/maven
  Build Configuration:
    $BP_MAVEN_BUILD_ARGUMENTS  -Dmaven.test.skip=true --no-transfer-progress package  the arguments to pass to Maven
    $BP_MAVEN_BUILT_ARTIFACT   target/*.[ejw]ar                                       the built application artifact explicitly.  Supersedes $BP_MAVEN_BUILT_MODULE
    $BP_MAVEN_BUILT_MODULE                                                            the module to find application artifact in
    $BP_MAVEN_DAEMON_ENABLED   false                                                  use maven daemon
    $BP_MAVEN_POM_FILE         pom.xml                                                the location of the main pom.xml file, relative to the application root
  Apache Maven 3.8.5: Contributing to layer
    Downloading from https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.8.5/apache-maven-3.8.5-bin.tar.gz
    Verifying checksum
    Expanding to /layers/paketo-buildpacks_maven/maven
    Creating cache directory /home/cnb/.m2
  
  I think this i a bug in the builder,  and that I know that i can temporary fix this by overriding the MAVEN_BUILD_ARGUEMENTS as stated.

**Comment by dmikusa-pivotal** [comment]
```
Executing mvnw --batch-mode -Dmaven.test.skip=true --no-transfer-progress package
```

In your original post, it says `mvnw`  ^^^. Are you certain?

I can take a closer look if you include the full output from building, as well as the full `pack build`command you're running. It's hard to say what might be happening without the full output.

**Comment by pax95** [comment]
Closing this now. Thanks for pointing me in the right direction :-)
