### ISSUE TITLE
Add Node into the buildpack order group

### ISSUE THREAD

**Issue by dmikusa** [paketo-buildpacks/java#651]
## What happened?

It is not uncommon to have a front-end and back-end app packaged together. The backend running on Java, of course :) and the front-end being HTML/Javascript. In this case, there are Maven/Gradle plugins that can be used to drive the build and also build the front-end assets and materials.

Right now, the same Maven/Gradle plugins would need to also install Node.js/NPM to work. We can add the `paketo-buildpacks/node-engine` buildpack to the order group and conditionally require it (probably from libbs) if one of the build tools requires Node.js/NPM.

This proposal would be to **only** install Node/NPM. Running commands would be up to Maven/Gradle. This is similar to how the Paketo Ruby buildpack installs Node.js/NPM and to enable Rails to build assets.

**Comment by anthonydahanne** [comment]
hello @voor,
Just out of curiosity, have you tried using the [frontend-maven-plugin](https://github.com/eirslett/frontend-maven-plugin) or rather in your case the  [gradle-frontend-plugin](https://siouan.github.io/frontend-gradle-plugin/) that auto installs `npm` and or `yarn` ? 
If so, did you encounter problems with them while trying to run your `build.gradle` with Paketo Java buildpack?
Thanks!

**Comment by voor** [comment]
We actually did, but then encounter an issue where if you're not able to hit the places those distributables can download node you're faced with a new problem (which is our situation)

**Comment by anthonydahanne** [comment]
> We actually did, but then encounter an issue where if you're not able to hit the places those distributables can download node you're faced with a new problem (which is our situation)

OK! in that case, couldn't you set a proxy to download from? From the [plugin documentation](https://github.com/eirslett/frontend-maven-plugin#installing-node-and-npm):

```xml
<!-- optional: where to download node and npm from. Defaults to https://nodejs.org/dist/ -->
        <downloadRoot>http://myproxy.example.org/nodejs/</downloadRoot>
```

But anyway, wouldn't you hit the same problem with a buildpack downloading `node` from the internet?

**Comment by voor** [comment]
> But anyway, wouldn't you hit the same problem with a buildpack downloading node from the internet?
No, because the buildpack could pre-cache/pre-stage the download similar to how it handles gradle wrapper and maven wrapper.  In the gradle plugin this can be achieved with [`download = false`](https://github.com/node-gradle/gradle-node-plugin/blob/master/docs/usage.md), and it looks like for maven they recommend using `exec-maven-plugin` for that use case, although I'm not as familiar with the plugin you're referring to.

**Comment by johnnyr0x** [comment]
@dmikusa any chance you are free today to review these PR's?
