### ISSUE TITLE
OpenJDK error with cgroups v2

### ISSUE THREAD

**Issue by corneil** [paketo-buildpacks/java#680]
OpenJDK cgroups v2 bug: 
[JDK-8283559](https://bugs.openjdk.org/browse/JDK-8283559) 

## Expected Behaviour
OpenJDK should select SerialGC for 1 CPU.

## Current Behavior
OpenJDK select G1GC which impacts performance.

## Possible Solution
Upgrade to JDK 11.0.16 and other relevant versions mentioned in OpenJDK issue.

**Comment by dmikusa-pivotal** [comment]
I suspect that this will get resolved in the [July 2022 quarterly updates](https://www.oracle.com/security-alerts/#CriticalPatchUpdates). I can ask and try to confirm with our JVM Vendor.

In the meantime, you can adjust GC settings by setting the env variable `JAVA_TOOL_OPTIONS` when you run your application. Just include any GC settings you want and the JVM will read them from that env variable.

Alternatively, you could use the [environment variables CNB](https://paketo.io/docs/howto/configuration/#environment-variables) and it would allow you to bake that env variable values for `JAVA_TOOL_OPTIONS` into the image itself. That way you only need to set it at build and it'll just apply at runtime.

**Comment by corneil** [comment]
The new releases are available. https://github.com/bell-sw/Liberica/releases/tag/11.0.16%2B8

**Comment by dmikusa-pivotal** [comment]
Version https://github.com/paketo-buildpacks/java/releases/tag/v6.32.0 was cut about an hour ago and has the updated versions of JDK/JREs. That includes 11.0.16.

Please give it a try and let me know if you're still seeing this issue. thanks!

**Comment by corneil** [comment]
Thank you very much

**Comment by corneil** [comment]
@dmikusa-pivotal Does this mean the change will also be in the base image for Spring Boot?

**Comment by dmikusa-pivotal** [comment]
Yes, usually the builder tiny/base/full images update about 15-20 mins after we publish. I just checked and they are updated. If you're not seeing the change, run a `docker pull` or make sure you set the `pull-policy` to `always` so it fetches new images.
