### ISSUE TITLE
Implement RFC0052: Graceful Stack Upgrades

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/java#741]
[RFC](https://github.com/paketo-buildpacks/rfcs/blob/main/text/0052-graceful-stack-upgrades.md)

## Summary

All Paketo Buildpacks should support graceful stack upgrades between the current Bionic and Jammy stacks. For most buildpacks, this should not require any changes, but for some buildpacks, layers created in previous builds that would normally be reused should be recreated if the stack ID changes.

## Action Item
Consider what types of buildpacks would be impacted by a stack upgrade and make any relevant changes that would help to mitigate issues caused by that upgrade. If there is no work to be done, please comment on this issue explaining the context that helped to arrive at that conclusion.

**Comment by pivotal-david-osullivan** [comment]
For Java, we made the following changes to support Jammy:

- https://github.com/paketo-buildpacks/libjvm/pull/200
- https://github.com/paketo-buildpacks/apache-tomcat/pull/248 
- https://github.com/paketo-buildpacks/native-image/pull/169

These set relevant paths to be writable by the CNB group, allowing more flexibility for Jammy UIDs, as well as including Jammy-Tiny in the list of `native-image` stacks checked when adding a tiny-specific argument.

**Comment by ryanmoran** [comment]
Does that mean that this is done?

**Comment by dmikusa** [comment]
For Java buildpacks (and others based on libpak), yes, I believe so.
