### ISSUE TITLE
repo.spring.io brown-out process is breaking spring boot builds

### ISSUE THREAD

**Issue by stoiev** [paketo-buildpacks/java#882]
`repo.spring.io` is being deprecated in favor of Maven Central, and it is under [brown-out process](https://spring.io/blog/2022/12/14/notice-of-permissions-changes-to-repo-spring-io-january-2023).

Builds that depends on [paketo-buildpacks/spring-boot](https://github.com/paketo-buildpacks/spring-boot) are breaking during brown-out periods. Next one is tomorrow (12/01/2023), and it will take 4 hours.

This issue was already resolved in https://github.com/paketo-buildpacks/spring-boot/pull/306, but this project need to be update to paketo-buildpacks/spring-boot v5.22.1 to get the fix.

## Expected Behavior
Spring boot builds being always successful.

## Current Behavior
Spring boot builds breaking at [brown-out times](https://spring.io/blog/2022/12/14/notice-of-permissions-changes-to-repo-spring-io-january-2023).
```
    [creator]     Paketo Buildpack for Spring Boot 5.20.0
    [creator]       https://github.com/paketo-buildpacks/spring-boot
    [creator]       Build Configuration:
    [creator]         $BP_SPRING_CLOUD_BINDINGS_DISABLED   false  whether to contribute Spring Boot cloud bindings support
    [creator]       Launch Configuration:
    [creator]         $BPL_SPRING_CLOUD_BINDINGS_DISABLED  false  whether to auto-configure Spring Boot environment properties from bindings
    [creator]         $BPL_SPRING_CLOUD_BINDINGS_ENABLED   true   Deprecated - whether to auto-configure Spring Boot environment properties from bindings
    [creator]       Creating slices from layers index
    [creator]         dependencies (73.8 MB)
    [creator]         spring-boot-loader (282.2 KB)
    [creator]         snapshot-dependencies (0.0 B)
    [creator]         application (8.9 MB)
    [creator]       Launch Helper: Contributing to layer
    [creator]         Creating /layers/paketo-buildpacks_spring-boot/helper/exec.d/spring-cloud-bindings
    [creator]       Spring Cloud Bindings 1.10.0: Contributing to layer
    [creator]         Downloading from https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.10.0/spring-cloud-bindings-1.10.0.jar
    [creator]     unable to invoke layer creator
    [creator]     unable to contribute spring-cloud-bindings layer
    [creator]     unable to get dependency spring-cloud-bindings
    [creator]     unable to download https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.10.0/spring-cloud-bindings-1.10.0.jar
    [creator]     could not download https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.10.0/spring-cloud-bindings-1.10.0.jar: 401
    [creator]     ERROR: failed to build: exit status 1
```

## Possible Solution
Just run [pb-update-spring-boot.yml](https://github.com/paketo-buildpacks/java/blob/main/.github/workflows/pb-update-spring-boot.yml) workflow manually, and merge the generated pull request.

## Steps to Reproduce
Under [brown-out times](https://spring.io/blog/2022/12/14/notice-of-permissions-changes-to-repo-spring-io-january-2023):
1. Create a sample buildpack Java application with the Spring Boot buildpack selected and the SpringBoot Gradle plugin included.
2. Run gradle bootBuildImage

## Motivations
No more builds breaking :)

**Comment by dmikusa** [comment]
Please standby. There should be a new Java composite buildpack shortly. Builders should update 15-30 minutes after that is released.

**Comment by stoiev** [comment]
https://github.com/paketo-buildpacks/java/pull/885 will resolve this issue

**Comment by pivotal-david-osullivan** [comment]
The latest builder is now live and contains the fix for this issue!

**Comment by dmikusa** [comment]
We have had a second brown-out and this issue did not come up again, so I'm going to mark this as resolved.
